version: "3"
services:
  app-node:
    container_name: app-node
    build:
      context: .
      dockerfile: ./docker/app/app.Dockerfile
    ports:
      - "3000:3000"
      - "8080:8080"
    depends_on:
      - "dynamodb"
    links:
      - "dynamodb"
    environment:
      - AWS_ACCESS_KEY_ID=DUMMYIDEXAMPLE
      - AWS_SECRET_ACCESS_KEY=DUMMYEXAMPLEKEY
      - REGION=eu-west-1
      - DYNAMO_ENDPOINT=http://dynamodb:8000

  dynamodb:
    build:
      context: ./docker/db
      dockerfile: db.Dockerfile
    container_name: dynamodb
    expose:
      - 8000
    environment:
      - AWS_ACCESS_KEY_ID=DUMMYIDEXAMPLE
      - AWS_SECRET_ACCESS_KEY=DUMMYEXAMPLEKEY
      - REGION=eu-west-1
    ports:
      - "8000:8000"
